export * from "../Mobile/HeadlineSectionMobile";
export * from "./ProblemsSectionMobile";
export * from "../Mobile/TargetAudienceSectionMobile";
export * from "./WhyUsSectionMobile";
export * from "./CourseProgramSectionMobile";
export * from "./FaqSectionMobile";
export * from "./ResultsSectionMobile";
export * from "./ReviewsSectionMobile";
export * from "./TicketSectionMobile";
